<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-UK1UHLE" ignored="6" name="Default test" tests="30" failures="4" timestamp="2021-09-30T22:04:11 EEST" time="0.781" errors="0">
  <testcase name="testStringToNumber" time="0.031" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.015" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.016" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.015" classname="com.ss.ita.kata.EightTest">
    <failure type="java.lang.AssertionError" message="expected [-10] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-10] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.ss.ita.kata.EightTest.testStringToNumber(EightTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testStringToNumber -->
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest">
    <failure type="java.lang.AssertionError" message="expected [10] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.ss.ita.kata.EightTest.testStringToNumber(EightTest.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testStringToNumber -->
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.016" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.015" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.016" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.016" classname="com.ss.ita.kata.EightTest">
    <failure type="java.lang.AssertionError" message="expected [-10] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [-10] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.ss.ita.kata.EightTest.testStringToNumber(EightTest.java:40)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testStringToNumber -->
  <testcase name="testStringToNumber" time="0.015" classname="com.ss.ita.kata.EightTest"/>
  <testcase name="testStringToNumber" time="0.0" classname="com.ss.ita.kata.EightTest">
    <failure type="java.lang.AssertionError" message="expected [10] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [10] but found [0]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.ss.ita.kata.EightTest.testStringToNumber(EightTest.java:40)
at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testStringToNumber -->
  <testcase name="testAmIWilson" time="0.0" classname="com.ss.ita.kata.EightTest">
    <ignored/>
  </testcase> <!-- testAmIWilson -->
  <testcase name="testVolumeOfCuboid" time="0.0" classname="com.ss.ita.kata.EightTest">
    <ignored/>
  </testcase> <!-- testVolumeOfCuboid -->
  <testcase name="testDivisibleBy" time="0.0" classname="com.ss.ita.kata.EightTest">
    <ignored/>
  </testcase> <!-- testDivisibleBy -->
  <testcase name="testLiters" time="0.0" classname="com.ss.ita.kata.EightTest">
    <ignored/>
  </testcase> <!-- testLiters -->
  <testcase name="testMpgToKPM" time="0.0" classname="com.ss.ita.kata.EightTest">
    <ignored/>
  </testcase> <!-- testMpgToKPM -->
  <testcase name="testCountPositivesSumNegatives" time="0.0" classname="com.ss.ita.kata.EightTest">
    <ignored/>
  </testcase> <!-- testCountPositivesSumNegatives -->
</testsuite> <!-- Default test -->
